### ISSUE TITLE
Global :attr not allowed in slot

### ISSUE THREAD

**Issue by nathanmalishev** [woylie/flop_phoenix#135]
**Describe the bug**
Looks like Phoenix LiveView 0.18.3, added a raise to `global` within slot attr.
See https://github.com/phoenixframework/phoenix_live_view/issues/2164 && https://github.com/phoenixframework/phoenix_live_view/issues/2265

**To Reproduce**
Install Phoenix LiveView 0.18.3 & FlopPhoenix, you receive a compile error.

`== Compilation error in file lib/flop_phoenix.ex ==
** (CompileError) lib/flop_phoenix.ex:660: cannot define :global slot attributes
    (phoenix_live_view 0.18.3) lib/phoenix_component/declarative.ex:526: Phoenix.Component.Declarative.compile_error!/3
    (phoenix_live_view 0.18.3) lib/phoenix_component/declarative.ex:251: Phoenix.Component.Declarative.__slot__!/6
    lib/flop_phoenix.ex:628: (module)`

**Versions:**
 - Flop.Phoenix: 0.16.0
 - Phoenix.LiveView: 0.18.3

**Comment by nathanmalishev** [comment]
Fixed in v0.17.0
